#!/bin/bash

command -v module >/dev/null 2>&1 && echo "Adding some modules" && module add cmake-3.18.3 llvm-9.0.1

echo "#################"
echo "    COMPILING    "
echo "#################"
mkdir cmake-build-debug >/dev/null 2>&1
cd cmake-build-debug || exit
CC=$(which clang) CXX=$(which clang++) cmake ..
make

echo "#################"
echo "     RUNNING     "
echo "#################"
./pv021_project

echo "#################"
echo "    EVALUATING   "
echo "#################"
python3 ./python_evaluator/evaluate.py ./out/actualTestPredictions ./data/fashion_mnist_test_labels.csv
