#!/bin/bash

command -v module && echo "Adding some modules" && module add cmake llvm

echo "#################"
echo "    COMPILING    "
echo "#################"
mkdir cmake-build-debug
cd cmake-build-debug || exit
cmake ..
make

echo "#################"
echo "     RUNNING     "
echo "#################"
./pv021_project

echo "#################"
echo "    EVALUATING   "
echo "#################"
python3 ./python_evaluator/evaluate.py ./out/actualTestPredictions ./data/fashion_mnist_test_labels.csv
