#!/bin/bash

echo "#################"
echo "    COMPILING    "
echo "#################"
command -v module >/dev/null 2>&1 && echo "Adding GCC 10.2..." && module add gcc-10.2
mkdir build >/dev/null 2>&1
cd build || exit
echo "Compiling main..." && g++ ../src/main.cpp -Ofast -ffp-contract=fast -funsafe-math-optimizations -march=native -fopenmp -msse2 -mfpmath=sse -ftree-vectorize -std=c++17 || exit

echo "#################"
echo "     RUNNING     "
echo "#################"
mkdir ../out >/dev/null 2>&1
./a.out

echo "#################"
echo "    EVALUATING   "
echo "#################"
python3 ../python_evaluator/evaluate.py ../out/actualTestPredictions ../data/fashion_mnist_test_labels.csv
